name: Release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  release:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Swift
        uses: swift-actions/setup-swift@v2

      - name: Build executable
        run: |
          swift build -c release
          mkdir -p dist
          cp .build/release/SRoll dist/SRoll

      - name: Archive binary
        run: |
          cd dist
          tar -czvf sroll-macos.tar.gz sroll

      - name: Upload release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            sroll-macos.tar.gz